language: node_js
sudo: false
node_js:
  - "7"

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - cd testing && echo -en 'travis_fold:start:npm-install\r' && npm install && echo -en 'travis_fold:end:npm-install\r' && npm test
